sudo: false

language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

before_install:
  - yarn codecov.io

after_success:
  - yarn test:coverage
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - master
