sudo: false

language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - cd client

script:
  - yarn test
  - yarn lint

branches:
  only:
    - master
