version: "3"
services:
  web:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./client:/code/client:rw
    environment:
      - NODE_ENV=development
    ports:
      - "9000:9000"
